### ISSUE TITLE
hexadecimalLowercase and hexadecimalUppercase exports misspelled

### ISSUE THREAD

**Issue by jpricer** [CyberAP/nanoid-dictionary#18]
Both of the hexadecimal exports are misspelled as hecadecimalUppercase and hecadecimalLowercase

```js
// 
// /src/hexadecimal-uppercase.js
export const hecadecimalUppercase = numbers + 'ABCDEF';

// hexadecimal-lowercase.js
export const hecadecimalLowercase = numbers + 'abcdef';
```

**Comment by CyberAP** [comment]
Thank you! Fixed in the repo, will publish to npm some time later (with the 5.0 release).

**Comment by jpricer** [comment]
👍 Great!  And thanks for the helpful little package to play around with nanoid alphabets.
