### ISSUE TITLE
Uppercase + Numbers

### ISSUE THREAD

**Issue by mayankkataria** [CyberAP/nanoid-dictionary#25]
How to get combination of Uppercase(A-Z) + Numbers(0-9)? Is there any way to include multiple dictionaries like below?
`customAlphabet(uppercase, numbers, 10)`

**Comment by CyberAP** [comment]
`customAlphabet(uppercase + numbers, 10)`

**Comment by mayankkataria** [comment]
> `customAlphabet(uppercase + numbers, 10)`

Thanks a lot
