### ISSUE TITLE
Remove filename alphabet

### ISSUE THREAD

**Issue by ai** [CyberAP/nanoid-dictionary#3]
Nano ID 2.0 don’t use `~` anymore. We can remove `filename` alphabet (of course, it also uses `,`, but it is not so big deal).

**Comment by CyberAP** [comment]
It would break backwards compatibility for anyone who uses that alphabet.

**Comment by ai** [comment]
Good point. But Nano ID anyway released major version on these days. You can do the same.

Or keep it and just remove from docs.

**Comment by CyberAP** [comment]
Moved into legacy character sets to retain backwards compatibility.
