### ISSUE TITLE
Add a 'safe' dictionary without vowels and lookalikes

### ISSUE THREAD

**Issue by kripod** [CyberAP/nanoid-dictionary#6]
I think that a new dictionary based on 'lookalikes' could be created without vowels to avoid obscene words by accident:

```
6789BCDFGHJKLMNPQRTWXbcdfghjkmnpqrtwxz
```

I also excluded the numbers '3' and '4', as they may resemble 'E' and 'A', respectively. Also, `V` may be a substitute for the vowel `U`, so I removed that as well.

**Comment by CyberAP** [comment]
There's actually a package that can do exactly that: https://github.com/y-gagar1n/nanoid-good

**Comment by kripod** [comment]
That package works on fundamentally different principles. It’s computationally harder to filter for a (non-complete) list of profane words, rather than excluding vowels from an ABC so comprehensible words cannot be formed by accident.

**Comment by CyberAP** [comment]
I agree that they are not computationally equal. That might be reasonable to have a safe subset of a `nolookalikes` list. I've run it against Google profanity words and it seems to work just fine, though there's an `xxx` case and I wonder if it makes any sense to remove `x` letter as well. Do you have a specific word list you'd like to target against?

**Comment by kripod** [comment]
Thanks for being open about the idea! I don’t have a specific list to test against, just thought that the lack of vowels would satisfy the use-case. The letter 'x' is a nice catch, it should be removed as well with its uppercase variant, too:

```
6789BCDFGHJKLMNPQRTWbcdfghjkmnpqrtwz
```

**Comment by CyberAP** [comment]
Added in 4.1.0 https://github.com/CyberAP/nanoid-dictionary/commit/49c2c1be45c0b20e0b0cc1104b41ce2322abc1bc

**Comment by kripod** [comment]
Wonderful, thank you! 😊
